package com.example.SIGR.entity;

public enum AuditPropose {
    OPERATIONNEL_PERFORMANCE,
    CONFORMITE_REGULARITE,
    EVALUATION_FRAUDES_ERREURS,
    CONTROLE_INTERNE,
    VALIDATION_FIABILITE_INTEGRITE,
    AUDIT_SUIVI
}
