package com.example.SIGR.entity;

public enum TypeRisque {

    STRATEGIQUE_PILOTAGE,
    OPERATIONNEL,
    FINANCIER,
    RESSOURCES_HUMAINES,
    ETHIQUE_DEONTOLOGIE_FRAUDE,
    JURIDIQUE,
    INFORMATIQUE,
    IMAGE_REPUTATION,
    GESTION_CONNAISSANCE,
    EXTERNE
}