package com.example.SIGR.entity;

public enum TypeNotification {
    RISQUE_SANS_MITIGATION,
    RISQUE_SANS_ACTIONS_EN_COURS,
    INDICATEUR_SEUIL_DEPASSE,
    INDICATEUR_ECHEANCE_PROCHE,
    RISQUE_EN_ATTENTE_VALIDATION
}
